------------------------
-- 		  DDkL		  --
------------------------
CREATE SCHEMA APOTEK;

CREATE TABLE APOTEK.SUPPLIER (
	ID_SUPPLIER				VARCHAR(5) NOT NULL PRIMARY KEY,
	ALAMAT_SUPPLIER			VARCHAR(45)
);

CREATE TABLE APOTEK.APOTEKER (
	ID_AP					VARCHAR(5) NOT NULL PRIMARY KEY,
	NAMA_DEPAN				VARCHAR(20),
	NAMA_BELAKANG			VARCHAR(20),
	ALAMAT_TEMPAT_TINGGAL	VARCHAR(45),
	GENDER					CHAR(1) CHECK (GENDER IN ('P', 'W')),
	TGL_LAHIR				DATE,
	STRATA					VARCHAR(20),
	JURUSAN					VARCHAR(20),
	UNIVERSITAS				VARCHAR(45),
	TAHUN_LULUS				INTEGER
);

CREATE TABLE APOTEK.OBAT (
	ID_OBAT					VARCHAR(5) NOT NULL PRIMARY KEY,
	ID_AP					VARCHAR(5),
	NAMA_OBAT				VARCHAR(45),
	HARGA					INTEGER,
	CARA_MINUM				VARCHAR(255),
	FOREIGN KEY(ID_AP)
		REFERENCES APOTEK.APOTEKER(ID_AP)
);

CREATE TABLE APOTEK.SUPLAI (
	ID_OBAT					VARCHAR(5),
	ID_SUPPLIER				VARCHAR(5),
	FOREIGN KEY(ID_SUPPLIER)
		REFERENCES APOTEK.SUPPLIER(ID_SUPPLIER),
	FOREIGN KEY(ID_OBAT)
		REFERENCES APOTEK.OBAT(ID_OBAT)
);

CREATE TABLE APOTEK.PEMBELI (
	ID_PEMBELI				VARCHAR(5) NOT NULL PRIMARY KEY,
	NAMA_DEPAN				VARCHAR(20),
	NAMA_BELAKANG			VARCHAR(20),
	GENDER					CHAR(1) CHECK (GENDER IN ('P', 'W')),
	TGL_LAHIR				DATE
);

CREATE TABLE APOTEK.KARYAWAN (
	ID_KARYAWAN				VARCHAR(5) NOT NULL PRIMARY KEY,
	NAMA_DEPAN				VARCHAR(20),
	NAMA_BELAKANG			VARCHAR(20)
);

CREATE TABLE APOTEK.TRANSAKSI_PEMBELIAN (
	ID_PEMBELI				VARCHAR(5) NOT NULL,
	ID_KARYAWAN				VARCHAR(5) NOT NULL,
	ID_OBAT					VARCHAR(5) NOT NULL,
	JUMLAH_BARANG			INTEGER,
	WAKTU_TRANSAKSI			DATE,
	FOREIGN KEY(ID_PEMBELI)
		REFERENCES APOTEK.PEMBELI(ID_PEMBELI),
	FOREIGN KEY(ID_KARYAWAN)
		REFERENCES APOTEK.KARYAWAN(ID_KARYAWAN),
	FOREIGN KEY(ID_OBAT)
		REFERENCES APOTEK.OBAT(ID_OBAT)
);